name: kagi_demo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  bloc_notification:
    git:
      url: https://github.com/paulo-alves-lourenco/bloc_notification.git
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  fluttertoast: ^8.2.12
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  http: ^1.4.0
  injectable: ^2.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  mocktail: ^1.0.4

dev_dependencies:
  analyzer: ^7.4.5
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  import_sorter: ^4.6.0
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
